### ISSUE TITLE
is skidded and retarded and inefficient

### ISSUE THREAD

**Issue by Slappy826** [rosedevs/robloxaddygrabber#1]
please fix

**Comment by sloppey** [comment]
yespls

**Comment by YagUber** [comment]
I would much enjoy this to be fixed in the next version! I hate having to deal with this disgusting skidded shit, it's very annoying!

**Comment by TochigiV** [comment]
我吃屁股

**Comment by 3dsboy08** [comment]
ya

**Comment by rosedevs** [comment]
Whom aked for your oppinions. You're clearly here to prove a point, and the only thing 'skidded' is most probably the AOB Scanner. 

Now. If you clearly couldn't read the v3rm thread it's for others to understand how it'd work.

This was for others who were curious of how it worked, now i'm sure you all know how it'd work. So why are you here?

Eternal, i'm guessing you could 'slap your dick on your keyboard' and do this also. Correct?

Awesome, i'd appreciate it if you didn't reply back. Gooday lads.

**Comment by Slappy826** [comment]
ur a skid go away

**Comment by TochigiV** [comment]
I'll have you know that I am the only one here who is able to whip his dick out and slap it on his keyboard and make this piece of shit scanner. I am deeply offended that you thought some other skid, not me could do such a thing. You are such a noob.
